"""Groq Chat Client Infrastructure Abstraction.

Defines a minimal, infrastructure-internal client protocol and SDK wrapper
to enable straightforward unit testing of GroqGenerator without external API
calls or complex MagicMock chains.
"""

from collections.abc import Sequence
from typing import Protocol


class GroqChatClient(Protocol):
    """Internal client protocol for Groq chat completion API calls.

    Note: This protocol lives strictly within the Infrastructure layer.
    Domain and Application remain completely unaware of this interface.
    """

    def complete(
        self,
        *,
        model: str,
        messages: Sequence[dict[str, str]],
        temperature: float,
    ) -> str:
        """Executes a chat completion request and returns the model response text.

        Args:
            model: Target model identifier.
            messages: List of chat messages formatted with role and content.
            temperature: Sampling temperature.

        Returns:
            The raw text content generated by the model assistant.
        """
        ...


class GroqSdkChatClient:
    """Concrete Groq client adapter wrapping the official Groq Python SDK.

    Translates completion requests into official Groq SDK calls and extracts
    the generated assistant message text.
    """

    def __init__(self, api_key: str) -> None:
        """Initializes official Groq SDK client.

        Args:
            api_key: Valid secret Groq API authentication key.
        """
        from groq import Groq

        self._client = Groq(api_key=api_key)

    def complete(
        self,
        *,
        model: str,
        messages: Sequence[dict[str, str]],
        temperature: float,
    ) -> str:
        """Sends chat completion request to Groq API via official SDK.

        Args:
            model: Target model identifier on Groq.
            messages: Sequence of message dictionaries (role, content).
            temperature: Sampling temperature.

        Returns:
            Extracted text content from assistant response choice.

        Raises:
            RuntimeError: If the Groq API call fails or encounters provider errors.
        """
        try:
            response = self._client.chat.completions.create(
                model=model,
                messages=list(messages),
                temperature=temperature,
            )

            if not response.choices:
                return ""

            content = response.choices[0].message.content
            return content if content is not None else ""
        except Exception as exc:
            raise RuntimeError(f"Groq API generation request failed: {exc}") from exc
